<?php
error_reporting(E_ALL);
echo '<pre>',print_r($_POST,1),'</pre>';
echo 'Super man';
#$data = array();

# Обработка входных данных и помещение в массив для удобной работы в дальнейшем + лёгкая безопасность
$data['email']    = $_POST['anketaEmail'];
$data['username'] = $_POST['anketaContactDataUsername'];
$data['anketaContactDataLastname'] = $_POST['anketaContactDataLastname'];
$data['anketaContactDataDateOfBreach1'] = $_POST['anketaContactDataDateOfBreach1'];
$data['anketaContactDataDateOfBreach2'] = $_POST['anketaContactDataDateOfBreach2'];
$data['anketaContactDataDateOfBreach3'] = $_POST['anketaContactDataDateOfBreach3'];
$data['anketaContactDataSex'] 			= $_POST['anketaContactDataSex'];
$data['anketaContactDataAdressLive']	= $_POST['anketaContactDataAdressLive'];
$data['anketaContactDataPhoneNumber']	= $_POST['anketaContactDataPhoneNumber'];
$data['anketaContactDataJobPrefent']	= $_POST['anketaContactDataJobPrefent'];
$data['anketaLastWorkOne']				= $_POST['anketaLastWorkOne'];
$data['anketaLastWorkTwo']				= $_POST['anketaLastWorkTwo'];
$data['anketaLastWorkTree']				= $_POST['anketaLastWorkTree'];
$data['anketaLastWorkHawtimeNeed']		= $_POST['anketaLastWorkHawtimeNeed'];
$data['anketaLastWorkHuNowdadWork']		= $_POST['anketaLastWorkHuNowdadWork'];
$data['anketaLstWorkContactone']		= $_POST['anketaLstWorkContactone'];
$data['anketaLastWorkContacttwo']		= $_POST['anketaLastWorkContacttwo'];
$data['anketaLastWorkContactThree']		= $_POST['anketaLastWorkContactThree'];
$data['anketaLastWorkNowWork']			= $_POST['anketaLastWorkNowWork'];
$data['anketaLastWorkResultWork']		= $_POST['anketaLastWorkResultWork'];
$data['anketaLastWorkResultWorkTwo']	= $_POST['anketaLastWorkResultWorkTwo'];
$data['anketaLastWorkResultWorkTree']	= $_POST['anketaLastWorkResultWorkTree'];
$data['anketaLastWork1']			 	= $_POST['anketaLastWork1'];
$data['anketaLastWork2']			 	= $_POST['anketaLastWork2'];
$data['anketaLastWork3']			 	= $_POST['anketaLastWork3'];
$data['anketaLastWork4']			 	= $_POST['anketaLastWork4'];
$data['anketaMashineNow1']				= $_POST['anketaMashineNow1'];
$data['anketaMashineNow2']				= $_POST['anketaMashineNow2'];
$data['anketaMashineNow3']				= $_POST['anketaMashineNow3'];
$data['anketaMashineNow4']				= $_POST['anketaMashineNow4'];
$data['anketaMashineNow5']				= $_POST['anketaMashineNow5'];
$data['anketaMashineNow6']				= $_POST['anketaMashineNow6'];
$data['anketaMashineNow7']				= $_POST['anketaMashineNow7'];
$data['anketaMashineNow8']				= $_POST['anketaMashineNow8'];
$data['anketaMashineNow9']				= $_POST['anketaMashineNow9'];
$data['anketaMashineNowEttension']		= $_POST['anketaMashineNowEttension'];
$data['anketaLanguageNowEn']			= $_POST['anketaLanguageNowEn'];
$data['anketaLanguageNowGb']			= $_POST['anketaLanguageNowGb'];
$data['anketaLanguageNowFr']			= $_POST['anketaLanguageNowFr'];
$data['anketaLanguageNowIta']			= $_POST['anketaLanguageNowIta'];
$data['anketaLanguageNowSP']			= $_POST['anketaLanguageNowSP'];
$data['anketaLanguageNowOther']			= $_POST['anketaLanguageNowOther'];
$data['anketaMashineNowCorrectLanguage'] = $_POST['anketaMashineNowCorrectLanguage'];
$data['anketaWriteLang1']				 = $_POST['anketaWriteLang1'];
$data['anketaWriteLang2']			 	 = $_POST['anketaWriteLang2'];
$data['anketaWriteLang3']				 = $_POST['anketaWriteLang3'];
$data['anketaWriteLang4']				 = $_POST['anketaWriteLang4'];
$data['anketaWriteLang5']				 = $_POST['anketaWriteLang5'];
$data['anketaWriteLang6']			     = $_POST['anketaWriteLang6']
$data['anketaWriteLangAnother']			 = $_POST['anketaWriteLangAnother'];
$data['anketaPublic1']					 = $_POST['anketaPublic1'];
$data['anketaPublic2']					 = $_POST['anketaPublic2'];
$data['anketaPublic3']					 = $_POST['anketaPublic3'];
$data['anketaPublic4']					 = $_POST['anketaPublic4'];
$data['anketaPublic5']					 = $_POST['anketaPublic5'];
$data['anketaPublic6']					 = $_POST['anketaPublic6'];
$data['anketaHobby1']					 = $_POST['anketaHobby1'];
$data['anketaNewJob1']					 = $_POST['anketaNewJob1'];
$data['anketaNewJob2']					 = $_POST['anketaNewJob2'];
$data['anketaNewJob3']					 = $_POST['anketaNewJob3'];
$data['anketaNewJob4']					 = $_POST['anketaNewJob4'];
$data['anketaNewJob5']					 = $_POST['anketaNewJob5'];
$data['anketaNewJob6']					 = $_POST['anketaNewJob6'];
$data['anketaFinnance1']				 = $_POST['anketaFinnance1'];
$data['anketaFinnance2']				 = $_POST['anketaFinnance2'];
$data['anketaFinnance3']				 = $_POST['anketaFinnance3'];
$data['anketaFinnance4']				 = $_POST['anketaFinnance4'];
$data['anketaFinnance5']				 = $_POST['anketaFinnance5'];
$data['anketaFinnancePrice1']			 = $_POST['anketaFinnancePrice1'];
$data['anketaFinnancePrice2']			 = $_POST['anketaFinnancePrice2'];
$data['anketaFinnancePrice3']			 = $_POST['anketaFinnancePrice3'];
$data['anketaFinnancePrice4']			 = $_POST['anketaFinnancePrice4'];
$data['anketaFinnancePrice5Bonus']		 = $_POST['anketaFinnancePrice5Bonus'];
$data['anketaFinnanceZP']				 = $_POST['anketaFinnanceZP'];
$data['anketaFinnanceZP_1']				 = $_POST['anketaFinnanceZP_1'];
$data['anketaFinnanceHu1']				 = $_POST['anketaFinnanceHu1'];
$data['anketaFinnanceHu2']				 = $_POST['anketaFinnanceHu2'];
$data['anketaFinnanceHu3']				 = $_POST['anketaFinnanceHu3'];
$data['anketaFinnanceHu4']				 = $_POST['anketaFinnanceHu4'];
$data['anketaFinnanceHu5']				 = $_POST['anketaFinnanceHu5'];
$data['anketaFinnanceHu6']				 = $_POST['anketaFinnanceHu6'];
$data['anketaFinnanceHu7']				 = $_POST['anketaFinnanceHu7'];
$data['anketaFamaliHu1']				 = $_POST['anketaFamaliHu1'];
$data['anketaFamaliHu2']				 = $_POST['anketaFamaliHu2'];
$data['anketaFamaliHu3']			  	 = $_POST['anketaFamaliHu3'];
$data['anketaFamaliHu4']				 = $_POST['anketaFamaliHu4'];
$data['anketaFamaliHuChild1']			 = $_POST['anketaFamaliHuChild1'];
$data['anketaFamaliHuChild2']			 = $_POST['anketaFamaliHuChild2'];
$data['anketaFamaliHuChild3']			 = $_POST['anketaFamaliHuChild3'];
$data['anketaFamaliHuChild4']			 = $_POST['anketaFamaliHuChild4'];
$data['anketaCar1']						 = $_POST['anketaCar1'];
$data['anketaCar2']						 = $_POST['anketaCar2'];
$data['anketaCarA']						 = $_POST['anketaCarA'];
$data['anketaCarB']						 = $_POST['anketaCarB'];
$data['anketaCarC']						 = $_POST['anketaCarC'];
$data['anketaCarD']						 = $_POST['anketaCarD'];
$data['anketaCarE']						 = $_POST['anketaCarE'];
$data['anketaCarYes']					 = $_POST['anketaCarYes'];
$data['anketaCarNo']					 = $_POST['anketaCarNo'];
$data['anketaCarNoAnswer']				 = $_POST['anketaCarNoAnswer'];
$data['anketaSmokeYes']					 = $_POST['anketaSmokeYes'];
$data['anketaSmokeNot']					 = $_POST['anketaSmokeNot'];
$data['anketaSmokeNotAnswer']			 = $_POST['anketaSmokeNotAnswer'];
$data['anketaFinanceAprowed1']			 = $_POST['anketaFinanceAprowed1'];
$data['anketaFinish']					 = $_POST['anketaFinish'];



# Go send mail detail на сервере не отрабатывает ( [буду разбиратся]
// $to = 'fantom.seller@yandex.ru';
// $subject = 'Просто тема с сайта отправлена';
// $headers = "From: ".$data['email'];
// $message = 'Test message from Alexander'

// mail($to,$subject,$message,$headers);
